name: extrator_sped
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.0.3
  - pip
  - pip:
    - PyPDF2==3.0.1
    - pip>=21.0  # Atualiza o pip
    - setuptools>=50.0  # Atualiza o setuptools
    - wheel>=0.36  # Atualiza o wheel
    - spacy>=3.0,<4.0  # Instala a versão mais recente do spaCy 3.x