name: Delete Merged Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        run: |
          echo "PR was merged. Proceeding with branch deletion."

      - name: Delete branch
        if: github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "Deleting branch: $BRANCH_NAME"
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME"
